### PR TITLE
fix(States): Roughly polish states pages

### PR DESCRIPTION
**Pull request by weiweitoo**

### CODE REVIEW

**Review by tevanraj — COMMENTED** [review]
LGTM

**Comment by tevanraj** [comment]
@nazreen I don't have permission to merge it.

**Comment by nazreen** [comment]
@tevanraj that's because review is required, and you didn't post a review :P after there is review, then it can be merged.

**Review by nazreen — APPROVED** [review]
BEAUTIFUL @weiweitoo

**Comment by nazreen** [comment]
last requirement is that commits need to be signed.

https://help.github.com/en/articles/about-commit-signature-verification

@weiweitoo , you said you've set it up already right?

**Review by tevanraj — APPROVED** [review]

**Comment by tevanraj** [comment]
> @tevanraj that's because review is required, and you didn't post a review :P after there is review, then it can be merged.

still same. 
Screenshot 2019-03-13 at 11 48 56 AM

**Comment by weiweitoo** [comment]
@nazreen yeah. I have setup gpg key last time and it works in last commit. Not sure why does not work for this commit. Gonna find out later.

**Comment by openpromises** [comment]
Are you using ssh url as opposed to https?

**Comment by weiweitoo** [comment]
I am using the git cli with ssh key signin.

**Pull request merged**
